![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
my_array = np.arange(10)

print(my_array)

lista_impares = []
for i in range(len(my_array)):
    if my_array[i] % 2 != 0:
        lista_impares.append(my_array[i])

array_impares = np.array(lista_impares[::-1])
print(array_impares)

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


In [4]:
array_impares = my_array[my_array % 2 != 0][::-1]
print(array_impares)

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [27]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [ ]:
matriz_ejer4 = np.arange(1,21).reshape(4, 5)
print(matriz_ejer4)

print("-" * 20)

# Paso 1 = Seleccinamos todas las filas y tomamos todas las colunmas en orden inverso [::,::-1]
# Paso 2 = Tomamos todas las columnas en orden inverso [::-1]
matriz_ejer4_new = matriz_ejer4[::,::-1][::-1]
print(matriz_ejer4_new)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
--------------------
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [15]:
matriz_ejer5 = matriz_ejer4[0:2, 0:2]
print(matriz_ejer5)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [16]:
matriz_ejer6 = matriz_ejer4[0:3:2]
print(matriz_ejer6)

print("-" * 20)

columnas_impares = matriz_ejer6 % 2 != 0
matriz_ejer6_impares = matriz_ejer6[:, np.all(columnas_impares, axis=0)]

print(matriz_ejer6_impares)


[[ 1  2  3  4  5]
 [11 12 13 14 15]]
--------------------
[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [33]:
matriz_ejer7 = matriz_ejer4[0:3, ::-1]
print(matriz_ejer7)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [17]:
# Manera 1
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
z = np.array([])

for animal in x:
    if animal == "Loro":
        z = np.append(z, animal)

print(z)

['Loro' 'Loro']


In [20]:
# Manera 2 numpy
x == "Loro"

x_loro = x[x == "Loro"]
x_loro

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [16]:
ejer9 = np.arange(1, 21).reshape(2, 5, 2)
print(ejer9)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [21]:
ejer10 = np.full(10, 0)
print(ejer10)

print(ejer10.nbytes)

ejer10[3] = 1
ejer10

[0 0 0 0 0 0 0 0 0 0]
80


array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [27]:
ejer11 = np.arange(10,50)
print(ejer11)

print("-" * 80)

ejer11_invertido = ejer11[::-1]
print(ejer11_invertido)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
--------------------------------------------------------------------------------
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [34]:
ejer12 = np.array([1,2,0,0,4,0])
print(ejer12)
print(type(ejer12))

array_indices = np.where(ejer12 != 0)
print(array_indices)

[1 2 0 0 4 0]
<class 'numpy.ndarray'>
(array([0, 1, 4]),)


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [25]:
matriz_aleatorios = np.random.randint(100, size = (10,10))
print(matriz_aleatorios)

print("-" * 50)

# Usando funcion de numpy
print("Numero máximo: ", np.max(matriz_aleatorios))
# Usando metodo del objeto numpy.ndarray, matriz_aleatorios
print(matriz_aleatorios.max())

print("Numero mínimo: ", np.min(matriz_aleatorios))
print(matriz_aleatorios.min())

[[27 15 91 83 94 47 44 33 46 32]
 [59 69 25 17 72 47 75 69 46 28]
 [32 43 39 88 54 86 51 56 96 62]
 [43 37 34 72 80 20 37 63 42 89]
 [58 37 41 90 99 72 19 10 14 66]
 [52 83 39 90 17 18 67 58 66 52]
 [76 24  0 37 16 81 94 58 46 48]
 [44 37 73 27 59 21 25 88 18 92]
 [83 34 36 37 61 31 17 94 56 35]
 [62 18 30 43 54 63 36 61  1 46]]
--------------------------------------------------
Numero máximo:  99
99
Numero mínimo:  0
0


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
matriz_aleatorios_02 = np.random.randint(100, size=30)
print(matriz_aleatorios_02)

print("-" * 50)

# Usando funcion de numpy
print("Media: ", round(np.mean(matriz_aleatorios_02), 2))
# Usando metodo del objeto numpy.ndarray, matriz_aleatorios_02
round(matriz_aleatorios_02.mean(), 2)

[30 54 83 84 51 82 76 52 15  4 12 11 14 82 58 37 31 62 32 27 71 97 79 71
 30 62 85 55 18 43]
--------------------------------------------------
Media:  50.27


np.float64(50.27)

## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [29]:
matriz_ejer15 = np.full((10, 10), 0)
print(matriz_ejer15)

print("-" * 50)

matriz_ejer15[0:1][0:] = 1
matriz_ejer15[-1:][0:] = 1

matriz_ejer15[:, 0] = 1
matriz_ejer15[:, -1] = 1

print(matriz_ejer15)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
--------------------------------------------------
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [30]:
my_filter = ([True, False, True])

xy[0][my_filter] = 10
print(xy)


NameError: name 'xy' is not defined

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [31]:
matriz_ejer15 = np.full((8, 8), 0)
print(matriz_ejer15)

print("-" * 50)

matriz_ejer15[1::2, ::2] = 1  
matriz_ejer15[::2, 1::2] = 1  

print(matriz_ejer15)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
--------------------------------------------------
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [118]:
matriz_ejer17 = np.tile([[0,1], [1,0]], (4, 4))

print(matriz_ejer17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [142]:
matriz_aleatorios_03 = np.random.randint(1, 10, size = (5,5))
print(matriz_aleatorios_03)

print("-" * 20)

media_aleatorios = round(np.mean(matriz_aleatorios_03), 2)
print("Media de todos los numeros de la matriz: ", media_aleatorios)

desviacion_std = round(np.std(matriz_aleatorios_03), 2)
print("Desviación estándar: ", desviacion_std)

normalizacion = (matriz_aleatorios_03 - media_aleatorios) / desviacion_std

print(normalizacion)




[[4 6 5 8 1]
 [1 5 5 4 9]
 [7 3 1 9 1]
 [1 4 8 2 7]
 [4 8 6 9 9]]
--------------------
Media de todos los numeros de la matriz:  5.08
Desviación estándar:  2.81
[[-0.38434164  0.32740214 -0.02846975  1.03914591 -1.4519573 ]
 [-1.4519573  -0.02846975 -0.02846975 -0.38434164  1.39501779]
 [ 0.68327402 -0.74021352 -1.4519573   1.39501779 -1.4519573 ]
 [-1.4519573  -0.38434164  1.03914591 -1.09608541  0.68327402]
 [-0.38434164  1.03914591  0.32740214  1.39501779  1.39501779]]


In [ ]:
def sacar_media(array):
    suma = 0

    for fila in array:
        #print(fila)
        for num in fila:
            # print(num)
            suma = suma + num
    print("Suma de todos los numeros:", suma)
    media_numeros = suma / 25
    # print(media_numeros)
    return media_numeros


matriz_prueba = ([1,2,3,2,3,4,3,4,5,6],
                 [1,2,3,2,3,4,3,4,5,6])

media = sacar_media(matriz_prueba)
print("La media de los numeros del array es:", media)

Suma de todos los numeros: 66
La media de los numeros del array es: 2.64


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [148]:
secuencia_num = np.arange(11)
print(secuencia_num)

nuevo_array_01 = secuencia_num[(secuencia_num >= 3) & (secuencia_num <= 8)]
print(nuevo_array_01)

nuevo_array_02 = secuencia_num[~((secuencia_num >= 3) & (secuencia_num <= 8))]
print(nuevo_array_02)

[ 0  1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7 8]
[ 0  1  2  9 10]
