In [2]:
import numpy as np

### Lista de métodos vistos para los arrays.

Método arange (equivalente al range de python)

In [3]:
# Array del 0 al 9
print(np.arange(10))

# Del 0 al 9, con saltos de 2
print(np.arange(start=0,stop=10,step=2))

# Del 10 al 0, con saltos de -1
print(np.arange(10, 0, -1))

# Array de 0 al 10, con saltos de 0.5
print(np.arange(0, 10, 0.5))

# Especficiando el tipo de dato
print(np.arange(0, 10, 2, np.float16))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[0. 2. 4. 6. 8.]


Método random

In [4]:
# Si no se espcifica un rango, el que se coge por defecto es de 0 a 1
print(np.random.rand(20))

print("-" * 20)

# permite aplicar el round a todos los elementos, si no, tendriamos que iterar sobre todos los elementos 
array = np.random.rand(10)
print(np.round(array,2))

print("-" * 20)

# Matriz de numeros aleatorios
print(np.random.randint(5, size = (3,4)))

print("-" * 20)

# Lista unidimensional
print(np.random.randint(5,10, size = (10)))

print("-" * 20)

# Matriz bidimensional
print(np.random.randint(5,20, size = (3,4)))

[0.03057145 0.04818099 0.14776551 0.27652903 0.26057171 0.39302228
 0.35207596 0.44898219 0.6447991  0.4753712  0.70442671 0.37745639
 0.54675758 0.66726652 0.33861211 0.25856347 0.53236713 0.73747329
 0.35089788 0.85614294]
--------------------
[0.99 0.52 0.66 0.12 0.   0.33 0.06 0.46 0.19 0.96]
--------------------
[[1 0 3 1]
 [2 3 1 1]
 [0 2 1 2]]
--------------------
[9 9 5 6 9 6 7 9 7 7]
--------------------
[[14  5 16  5]
 [14 12 17  6]
 [11  8  5 18]]


#### Métodos para crear arrays o matrices

Matrices predefinidas con un único valor

- Método identidad

Es una matriz cuadrada (mismo número de filas y columnas) que tiene:

Todos los elementos de la diagonal principal iguales a 1

Todos los demás elementos iguales a 0

In [5]:
# Matriz identidad
print(np.identity(3))

# fila 0 columna 0 = 1
# fila 0 columna 1 = 0
# fila 0 columna 2 = 2

# fila 1 columna 0 = 0
# fila 1 columna 1 = 1
# fila 1 columna 2 = 0

# fila 2 columna 0 = 0
# fila 2 columna 1 = 0
# fila 2 columna 2 = 1

print("-" * 20)

print(np.identity(10))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


- Método zeros

Crea una matriz con todos los valores a 0

In [6]:
# Matriz de 0s
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- Método ones

Crea una matriz con todos los valores a 1

In [7]:
# Matriz de unos con tipo de datos int8
np.ones((3,3), np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

Matrices predefinidas introduciendo valor

In [8]:
array_02 = np.full((4,3), 10)
print(array_02)
print(array_02 * 2)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
[[20 20 20]
 [20 20 20]
 [20 20 20]
 [20 20 20]]


#### Atributos del array

In [9]:
array_multi = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(array_multi)

# Número de dimernsiones
print(array_multi.ndim)

# Tamaño de cada una de las dimensiones, devuelve una tupla
print(array_multi.shape)

# Cantidad de elementos del array
print(array_multi.size)

# Tamaño em bytes de los items del array
print(array_multi.itemsize)

# Tamaño em bytes de todo el array
print(array_multi.nbytes)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
8
72


#### INDEXADO, ACCESO A LOS ELEMENTOS DEL ARRAY

In [10]:
array_03 = np.random.randint(1, 101, size = (3,3,10))

array_03

array([[[ 25,  13,  16,  48,  88,   8,  52,  66,  59,  99],
        [ 67,  31,  34,  40,  22,  49,  81,  49,  81,  97],
        [ 11,  94,  22,  92,  72,  96,  43,  80,  34,  63]],

       [[ 63,  69,  87,  12,  38,  96,  77,  14,  23,  29],
        [ 61,  50,  52,  78,  87,   6,   2,   3,  94,  80],
        [ 45,   1,  62,  90,  52,   7,  51,  23,  17,   9]],

       [[ 36,  15,  17,   9,  98,  63,  49,  87,   4,  30],
        [ 78,  23,  46,  79,  67,  56,  78,  55,  90,   2],
        [ 99,  39,  23,  23,  72,   2,  34,  33,  41, 100]]], dtype=int32)

In [11]:
print(array_03[0])

print("-" * 20)

print(array_03[0])
print("-" * 20)
print(array_03[0][0])
print(array_03[0, 0])
print("-" * 20)
print(array_03[0][0][0])
print(array_03[0, 0, 0])
print("-" * 20)
print(array_03[0][0][2:5])
print(array_03[0, 0, 2:5])

[[25 13 16 48 88  8 52 66 59 99]
 [67 31 34 40 22 49 81 49 81 97]
 [11 94 22 92 72 96 43 80 34 63]]
--------------------
[[25 13 16 48 88  8 52 66 59 99]
 [67 31 34 40 22 49 81 49 81 97]
 [11 94 22 92 72 96 43 80 34 63]]
--------------------
[25 13 16 48 88  8 52 66 59 99]
[25 13 16 48 88  8 52 66 59 99]
--------------------
25
25
--------------------
[16 48 88]
[16 48 88]


### Slicing y subarrays

Sintaxis:

x[start:stop:step]

In [12]:
# Array de 10 elementos
x = np.arange(10)
print(x)

print("Del primer elemento al quinto", x[0:5])

print("Del primero al quinto con saltos de dos", x[0:5:2])

print("Desde el quinto", x[5::])
print("Desde el quinto", x[5:]) # equivalente

print("Desde el quinto hasta el penultimo", x[5:-1])

print("Desde el quinto, al primero", x[5::-1])

print("Sacar una copia", x[:])
print("Sacar una copia", x.copy())

print("Ultimos dos elementos",x[-2:])

[0 1 2 3 4 5 6 7 8 9]
Del primer elemento al quinto [0 1 2 3 4]
Del primero al quinto con saltos de dos [0 2 4]
Desde el quinto [5 6 7 8 9]
Desde el quinto [5 6 7 8 9]
Desde el quinto hasta el penultimo [5 6 7 8]
Desde el quinto, al primero [5 4 3 2 1 0]
Sacar una copia [0 1 2 3 4 5 6 7 8 9]
Sacar una copia [0 1 2 3 4 5 6 7 8 9]
Ultimos dos elementos [8 9]


#### MÁSCARA DE BOOLEANOS

In [13]:
x = np.array([2,4,5,2,3,7,2])

print(x)
print(x > 5)
array_mas_5 = [x > 5 ]
print(array_mas_5)

[2 4 5 2 3 7 2]
[False False False False False  True False]
[array([False, False, False, False, False,  True, False])]


In [14]:
x_bools = np.array(x >= 5)
print(x_bools)

print(x[x_bools])
# print(x_bools[x_bools])

[False False  True False False  True False]
[5 7]


In [15]:
x_new = x[x >= 5]
print(x_new)

[5 7]


In [16]:
# Sería el equivalente a esto

mi_lista = [2,4,5,2,3,7,2]
lista_filtrada = []

for elem in mi_lista:
    if elem >= 5:
        lista_filtrada.append(elem)

print(lista_filtrada)

[5, 7]


#### Función reshape

Sirve para cambiar las dimensiones de un array siempre que el número de elemmentos del arry lo permita.  Por ejemplo, si tenemos 4 elementos, no podremos hacer una matriz de 3x3.

In [17]:
x = np.arange(9)
print(x)

y = x.reshape((3,3))
print(y)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
x = np.arange(30).reshape(2,3,5) # 2 * 3 * 5
print(x)

print("--------------------")

x = np.arange(30).reshape((6,5)) # 6 * 5
print(x)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
--------------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [19]:
# Mete 6 filas, el -1 significa que meta columnas hasta que quepan 36 columanas
x = np.arange(30).reshape((6,-1))
print(x)

print("--------------------")

z = np.arange(30).reshape((-1,6))
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
--------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


#### Métodos para la concatenación

Hay que tener en cuenta es que coincidan las dimensiones, para que el concatenado sea correcto.

In [20]:
# El concatenado de las listas con Python no funciona igual que el de las series en Numpy.

print([1,2,3] + [1,2,3])

lista_01 = [1, 2, 3]
lista_02 = [4, 5, 6]
lista_concatenada = lista_01 + lista_02
print(lista_concatenada)

# En este caso se están sumando los valores de las columnas de los arrays
array_suma = np.array([1,2,3]) + np.array([1,2,3])
print(array_suma)
print(array_suma * 10)
print(array_suma / 2)
print(array_suma + 1)
print(array_suma - 1)
print(array_suma ** 2)

[1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5, 6]
[2 4 6]
[20 40 60]
[1. 2. 3.]
[3 5 7]
[1 3 5]
[ 4 16 36]


In [21]:
# Método concatenate
# Por defecto, el concatenado es horizontal

# Arrays unidimensionales
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate((x,y))

# Arrays bidimensionales (matrices)
xy = np.array([[1,2,3],
              [4,5,6]])

np.concatenate([xy,xy])

# En el caso de los arrays bidimensionales podemos jugar con las dimensiones y elegir el tipo de concatenado con el argumento axis.
xy_01 = np.concatenate([xy,xy], axis = 0) # Por defecto
print(xy_01)

print("--------------------")

xy_02 = np.concatenate([xy,xy], axis = 1)
print(xy_02)


[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
--------------------
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [22]:
# Para arrays de varias dimensiones puede ser mejor usar el método vstack para el concatenado vertical
xy = np.array([[1,2,3],
              [4,5,6]])

x = np.array([7,8,9])

np.vstack([xy,x])




array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# Para el concatenado horzontal se usaria hstack
zt = np.array([[1,2,3],
              [4,5,6]])

w = np.array([[7], [8]])
np.hstack([zt,w])

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

#### Sustitucion
En `numpy` podemos aplicar operaciones para sustituir elementos dependiendo de ciertas condiciones, y con esa sintaxis de sustitución también es posible filtrar datos de las matrices.

In [24]:
xy = np.array([[1,2,3],
              [4,5,6]])

print(xy[0,0:2]) # la posicion 2 no se muestra
print()

[1 2]



In [25]:
# Lista de booleanos aplicada al array
print(xy)

my_filter = ([True, False],[True, False,True]) # equivale a este slicing xy[0,0:2:2]
# filter = np.array([True, False, True])
xy[my_filter]

[[1 2 3]
 [4 5 6]]


array([1, 3])

In [26]:
my_filter = ([True, False, True])

xy[0][my_filter] = 10
print(xy)

[[10  2 10]
 [ 4  5  6]]


Método where. Sintaxis:

np.where(condición, x, y)

- condición = expresión booleana
- x = Valor que se elige cuando la condición es True.
- y = Valor que se elige cuando la condición es False.

In [27]:
xy = np.array([[1,2,3],
              [4,5,6]])


print(np.where(xy < 4, 10, 20))

print("-" * 20)

# En este caso, si la condición es False, se mantienen los valores del array
print(np.where(xy < 4, 10, xy))

[[10 10 10]
 [20 20 20]]
--------------------
[[10 10 10]
 [ 4  5  6]]


In [28]:
xy = np.array([[1,2,3],
              [4,5,6]])


print(np.where(xy < 4, 10, True))

[[10 10 10]
 [ 1  1  1]]


#### Copias
Una característica importante y extremadamente útil en los arrays es que cuando **hacemos *slicing*, realmente obtenemos de los arrays vistas, no copias**. ¿Esto qué significa? Que si hacemos *slicing*, creando un nuevo array, y lo modificamos, también estaremos modificando el original.

Esto difiere con las listas de Python, que al aplicar *slicing* lo que obtenemos es una copia, y por tanto cualquier modificación sobre la nueva lista no afectará a la lista original.

Declaro un array

In [29]:
x2 = np.ones((3, 4))
x2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[1. 1.]
 [1. 1.]]


In [31]:
# El array ha cambiado
x2_sub[0, 0] = 99
print(x2_sub)

[[99.  1.]
 [ 1.  1.]]


In [32]:
# Si no queremos modificar un array podemos hacer una copia
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99.  1.]
 [ 1.  1.]]


In [33]:
lista_1 = np.array([1,2,3,4,5])
lista_1_sub = lista_1[0:3].copy()
lista_1_sub[0]=10
print(lista_1_sub)
print(lista_1)

[10  2  3]
[1 2 3 4 5]


#### Splitting
Al igual que hacíamos el concatenado, podemos realizar la operación contraria mediante `np.split`, `np.hsplit` y `np.vsplit`. Le podemos pasar una lista de indices por los que realizar el split.

In [34]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
print(x)

print("-" * 20)

x1,x2 = np.split(x, 2)
print(x1)
print(x2)

print("-" * 20)

# En est caso, 2 y 5 indica los índices de división por los que se hace el corte
"""
índices:  0   1   2   3   4   5   6   7
x =      [1,  2,  3, 99, 99,  3,  2,  1]
             ^       ^
             2       5
"""

x1, x2, x3 = np.split(x, [2, 5])
print(x1)
print(x2)
print(x3)

print(x[:2])
print(x[2:5])
print(x[5:])

[ 1  2  3 99 99  3  2  1]
--------------------
[ 1  2  3 99]
[99  3  2  1]
--------------------
[1 2]
[ 3 99 99]
[3 2 1]
[1 2]
[ 3 99 99]
[3 2 1]


In [35]:
# serñia

print(x[:2])
print(x[2:5])
print(x[5:])

[1 2]
[ 3 99 99]
[3 2 1]


`np.hsplit` y `np.vsplit`

In [36]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
# se hace el split por la fila 2
upper, lower = np.vsplit(grid, [3])
print(upper)
print("-"*10)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------
[[12 13 14 15]]


In [38]:
left, right = np.hsplit(grid, [3])
print(left)
print("-"*10)
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
----------
[[ 3]
 [ 7]
 [11]
 [15]]


#### Agregaciones

Numpy ofrece métodos que permiten calcular estadísticas mediante agregaciones de los datos: media, mediana y desviación estándar.

SUMA

In [42]:
# SUMA
L = np.random.random(100)
print(L)
sum(L)

[0.6678386  0.11822493 0.97468055 0.16611178 0.70672887 0.59174256
 0.3018423  0.5482106  0.17031567 0.94139215 0.24227687 0.26434546
 0.08314016 0.52827896 0.7311672  0.42942835 0.74558339 0.17335701
 0.81800442 0.55477592 0.18716037 0.46305379 0.58197491 0.39406277
 0.64874085 0.37082923 0.73078571 0.57947236 0.60083586 0.92337251
 0.14835556 0.7198876  0.68630813 0.32561326 0.3884795  0.09783243
 0.92029572 0.82821752 0.82689762 0.64958043 0.61142322 0.54184197
 0.0408344  0.03281388 0.58574675 0.89467717 0.13095023 0.72709304
 0.61518194 0.93998355 0.640195   0.42413059 0.09171245 0.17028168
 0.43539052 0.28047117 0.89171049 0.44173454 0.66874281 0.97484631
 0.36238422 0.84775967 0.38625977 0.30021967 0.8062302  0.76480585
 0.94397812 0.5939447  0.00345034 0.03582933 0.85659144 0.89239414
 0.10730932 0.6044063  0.96049842 0.69118211 0.19157977 0.83652816
 0.27728911 0.88154894 0.29912905 0.74428648 0.16469704 0.62416917
 0.38419127 0.62640411 0.51019451 0.45492676 0.96106718 0.0485

np.float64(51.4423052032783)

In [ ]:
#
np.sum(L)

np.float64(51.4423052032783)

In [ ]:
"""
El %timeit es una "magic command" (comando mágico) de IPython o Jupyter Notebook que se usa para medir el 
tiempo de ejecución de una instrucción o bloque de código.
"""

big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

58.8 ms ± 2.48 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
394 μs ± 32.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


MIN Y MAX

In [47]:
# FUNCIONES DE PYTHON
min(big_array), max(big_array)

(np.float64(2.838274793082185e-06), np.float64(0.9999981977503771))

In [48]:
# MÉTODOS NUMPY 
np.min(big_array), np.max(big_array)

(np.float64(2.838274793082185e-06), np.float64(0.9999981977503771))

AGREGACIONES MULTIDEIMENSIONALES